stages:
  # - test
  - push

variables:
  SSH_KEY: ${SUPERBOT_SSH_KEY}

# Golang-Test:
#   stage: test
#   image: golang:1.11.0
#   script:
#     - make update-vendor
#     - make test
#     - make build

Golang-Docker-Push-Staging:
  stage: push
  image: google/cloud-sdk
  services:
    - docker:dind
  variables:
    GCLOUD_SERVICE_KEY: $GCR_SSTV_KEY_STAG
    GCLOUD_PROJECT_ID: $GCR_SSTV_PROJECT_STAG
    REPOSITORY_HOST: asia.gcr.io
    DOCKER_HOST: tcp://localhost:2375
  script:
    - .gitlab/auth_gcloud.sh
    - .gitlab/push_docker.sh
  only:
    - "develop@apps/molanobar/api/molanobar-core"

Golang-Docker-Push-Production:
  stage: push
  image: google/cloud-sdk
  services:
    - docker:dind
  variables:
    GCLOUD_SERVICE_KEY: $GCR_SSTV_KEY_PROD
    GCLOUD_PROJECT_ID: $GCR_SSTV_PROJECT_PROD
    REPOSITORY_HOST: asia.gcr.io
    DOCKER_HOST: tcp://localhost:2375
  script:
    - .gitlab/auth_gcloud.sh
    - .gitlab/push_docker.sh
  only:
    - "master@apps/molanobar/api/molanobar-core"